// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SitioMVC.Datos;

#nullable disable

namespace SitioMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251216170218_TablaReportesImagenesEnParalelo")]
    partial class TablaReportesImagenesEnParalelo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Comunes.Modelos.ImagenProcesoParalelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EstadoImagenProcesoParalelo")
                        .HasColumnType("int");

                    b.Property<Guid>("ReporteProcesoParaleloImagenesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReporteProcesoParaleloImagenesId");

                    b.ToTable("ImagenProcesoParalelo");
                });

            modelBuilder.Entity("Comunes.Modelos.Reporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorreoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReporteEstatus")
                        .HasColumnType("int");

                    b.Property<string>("ReporteURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("Comunes.Modelos.ReporteProcesoParaleloImagenes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorreoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReportesProcesoParaleloImagenes");
                });

            modelBuilder.Entity("SitioMVC.Models.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Comunes.Modelos.ImagenProcesoParalelo", b =>
                {
                    b.HasOne("Comunes.Modelos.ReporteProcesoParaleloImagenes", "ReporteProcesoParaleloImagenes")
                        .WithMany("Imagenes")
                        .HasForeignKey("ReporteProcesoParaleloImagenesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReporteProcesoParaleloImagenes");
                });

            modelBuilder.Entity("Comunes.Modelos.ReporteProcesoParaleloImagenes", b =>
                {
                    b.Navigation("Imagenes");
                });
#pragma warning restore 612, 618
        }
    }
}
